// src/debug/mockKernel.ts
import type { FullSnapshotPayload, WorldStore } from "../state/worldStore";

/**
 * DEV-ONLY: Inject a fake FULL_SNAPSHOT into the WorldStore
 * so we can validate the viewer render pipeline without a kernel.
 */
export function injectMockSnapshot(store: WorldStore): void {
    const snap: FullSnapshotPayload = {
        schema_version: "1",
        tick: 1,
        step_hash: "dev_mock_step_hash_0001",
        state: {
            rooms: [
                {
                    room_id: 1,
                    label: "Plaza",
                    kind_code: 0,
                    occupants: [101, 102],
                    items: [201],
                    neighbors: [2],
                    tension_tier: "low",
                    highlight: false,
                    bounds: { min_x: 1, min_y: 1, max_x: 4, max_y: 4 },
                    zone: "residential",
                    level: 0,
                },
                {
                    room_id: 2,
                    label: "Alley",
                    kind_code: 1,
                    occupants: [103],
                    items: [202],
                    neighbors: [1, 3],
                    tension_tier: "medium",
                    highlight: false,
                    bounds: { min_x: 4.5, min_y: 1.2, max_x: 7.2, max_y: 4.8 },
                    zone: "work",
                    level: 0,
                },
                {
                    room_id: 3,
                    label: "Cafe",
                    kind_code: 2,
                    occupants: [104],
                    items: [203],
                    neighbors: [2],
                    tension_tier: "high",
                    highlight: true,
                    bounds: { min_x: 7.6, min_y: 0.8, max_x: 10.0, max_y: 3.8 },
                    zone: "support",
                    level: 1,
                },
            ],
            agents: [
                {
                    agent_id: 101,
                    room_id: 1,
                    role_code: 0,
                    generation: 0,
                    profile_traits: {},
                    identity_vector: [],
                    persona_style_vector: null,
                    drives: {},
                    emotions: {},
                    key_relationships: [],
                    active_motives: [],
                    plan: null,
                    transform: { room_id: 1, x: 2.2, y: 1.2 },
                    action_state_code: 0,
                    narrative_state_ref: null,
                    cached_summary_ref: null,
                },
                {
                    agent_id: 102,
                    room_id: 1,
                    role_code: 1,
                    generation: 0,
                    profile_traits: {},
                    identity_vector: [],
                    persona_style_vector: null,
                    drives: {},
                    emotions: {},
                    key_relationships: [],
                    active_motives: [],
                    plan: null,
                    transform: { room_id: 1, x: 1.4, y: 2.0 },
                    action_state_code: 1,
                    narrative_state_ref: null,
                    cached_summary_ref: null,
                },
                {
                    agent_id: 103,
                    room_id: 2,
                    role_code: 2,
                    generation: 0,
                    profile_traits: {},
                    identity_vector: [],
                    persona_style_vector: null,
                    drives: {},
                    emotions: {},
                    key_relationships: [],
                    active_motives: [],
                    plan: null,
                    transform: { room_id: 2, x: 5.2, y: 2.8 },
                    action_state_code: 2,
                    narrative_state_ref: null,
                    cached_summary_ref: null,
                },
                {
                    agent_id: 104,
                    room_id: 3,
                    role_code: 3,
                    generation: 0,
                    profile_traits: {},
                    identity_vector: [],
                    persona_style_vector: null,
                    drives: {},
                    emotions: {},
                    key_relationships: [],
                    active_motives: [],
                    plan: null,
                    transform: { room_id: 3, x: 7.6, y: 1.4 },
                    action_state_code: 3,
                    narrative_state_ref: null,
                    cached_summary_ref: null,
                },
            ],
            items: [
                { item_id: 201, room_id: 1, owner_agent_id: null, status_code: 0, label: "Neon Sign" },
                { item_id: 202, room_id: 2, owner_agent_id: null, status_code: 0, label: "Crate" },
                { item_id: 203, room_id: 3, owner_agent_id: null, status_code: 0, label: "Espresso" },
            ],
            events: [
                {
                    tick: 1,
                    event_id: 1,
                    origin: "world",
                    payload: { kind: "mock_event", room_id: 1 },
                },
            ],
            debug: { note: "mock snapshot" },
        },
    };

    store.applySnapshot(snap);
}
