"""Backend API surface for Enqueteur playability flows."""

from .cases_start import (
    CASE_START_PATH,
    ENQUETEUR_ENGINE_NAME,
    ENQUETEUR_SCHEMA_VERSION,
    CaseStartRequest,
    CaseStartResponse,
    CaseStartService,
    StartCaseMode,
)
from .live_ws import (
    ENQUETEUR_ALLOWED_CHANNELS,
    ENQUETEUR_LIVE_WS_PATH,
    PROTOCOL_VIOLATION_WS_CLOSE_CODE,
    PROTOCOL_VIOLATION_WS_CLOSE_REASON,
    RUN_NOT_FOUND_WS_CLOSE_CODE,
    RUN_NOT_FOUND_WS_CLOSE_REASON,
    EnqueteurLiveSession,
    EnqueteurLiveSessionHost,
    EnqueteurSubscribedConfig,
    EnqueteurViewerHello,
    ProtocolViolationError,
    RunLookupError,
    get_default_enqueteur_live_session_host,
    handle_enqueteur_live_incoming_message,
    open_enqueteur_live_websocket,
    stream_enqueteur_frame_diff_loop,
    stream_enqueteur_frame_diff_once,
)
from .router import ApiRequest, ApiResponse, build_default_router

__all__ = [
    "ApiRequest",
    "ApiResponse",
    "CASE_START_PATH",
    "ENQUETEUR_ALLOWED_CHANNELS",
    "ENQUETEUR_LIVE_WS_PATH",
    "ENQUETEUR_ENGINE_NAME",
    "ENQUETEUR_SCHEMA_VERSION",
    "PROTOCOL_VIOLATION_WS_CLOSE_CODE",
    "PROTOCOL_VIOLATION_WS_CLOSE_REASON",
    "RUN_NOT_FOUND_WS_CLOSE_CODE",
    "RUN_NOT_FOUND_WS_CLOSE_REASON",
    "CaseStartRequest",
    "CaseStartResponse",
    "CaseStartService",
    "EnqueteurLiveSession",
    "EnqueteurLiveSessionHost",
    "EnqueteurSubscribedConfig",
    "EnqueteurViewerHello",
    "ProtocolViolationError",
    "RunLookupError",
    "StartCaseMode",
    "build_default_router",
    "get_default_enqueteur_live_session_host",
    "handle_enqueteur_live_incoming_message",
    "open_enqueteur_live_websocket",
    "stream_enqueteur_frame_diff_loop",
    "stream_enqueteur_frame_diff_once",
]
