"""MBAM Case Truth package (Enqueteur v1.0 Phase 1A).

This package owns deterministic, non-physical case truth for:
- roles and overlays
- evidence placement
- truth/contradiction graph
- scene gates and resolution rules

World Truth remains in backend.sim4.world.
"""

from .interface import CaseTruthProvider, MbamCaseBundle
from .models import (
    AlibiClaim,
    AlibiMatrix,
    AlibiTruthValue,
    AllyId,
    BenchEvidence,
    BestOutcomeRule,
    CafeEvidence,
    CaseState,
    CastOverlay,
    CharacterOverlay,
    CorridorEvidence,
    CulpritId,
    DifficultyProfile,
    DisplayCaseEvidence,
    DropId,
    DropLocationEvidence,
    EvidencePlacement,
    Helpfulness,
    HiddenCaseSlice,
    MethodId,
    MisdirectorId,
    ResolutionRequirement,
    ResolutionRules,
    RoleAssignment,
    SceneCompletionState,
    SceneGate,
    SceneGates,
    SceneId,
    SoftFailRule,
    TimelineBeat,
    TimelineBeatType,
    TruthEdgeRelation,
    TruthGraph,
    TruthGraphEdge,
    TruthGraphNode,
    TruthNodeType,
    TruthVisibility,
    VisibleCaseSlice,
)
from .scaffold import (
    SeedRoleLock,
    ShippedSeed,
    get_seed_role_lock,
    make_default_cast_overlay,
    make_empty_case_state_shell,
    make_roles_assignment_from_seed_lock,
)

__all__ = [
    "AlibiClaim",
    "AlibiMatrix",
    "AlibiTruthValue",
    "AllyId",
    "BenchEvidence",
    "BestOutcomeRule",
    "CafeEvidence",
    "CaseState",
    "CaseTruthProvider",
    "CastOverlay",
    "CharacterOverlay",
    "CorridorEvidence",
    "CulpritId",
    "DifficultyProfile",
    "DisplayCaseEvidence",
    "DropId",
    "DropLocationEvidence",
    "EvidencePlacement",
    "Helpfulness",
    "HiddenCaseSlice",
    "MbamCaseBundle",
    "MethodId",
    "MisdirectorId",
    "ResolutionRequirement",
    "ResolutionRules",
    "RoleAssignment",
    "SceneCompletionState",
    "SceneGate",
    "SceneGates",
    "SceneId",
    "SeedRoleLock",
    "ShippedSeed",
    "SoftFailRule",
    "TimelineBeat",
    "TimelineBeatType",
    "TruthEdgeRelation",
    "TruthGraph",
    "TruthGraphEdge",
    "TruthGraphNode",
    "TruthNodeType",
    "TruthVisibility",
    "VisibleCaseSlice",
    "get_seed_role_lock",
    "make_default_cast_overlay",
    "make_empty_case_state_shell",
    "make_roles_assignment_from_seed_lock",
]
