"""MBAM Case Truth package (Enqueteur v1.0 Phase 1A).

This package owns deterministic, non-physical case truth for:
- roles and overlays
- evidence placement
- truth/contradiction graph
- scene gates and resolution rules

World Truth remains in backend.sim4.world.
"""

from .interface import CaseTruthProvider, MbamCaseBundle
from .cast_registry import (
    CastIdentityEntry,
    FixedCastId,
    IdentityRole,
    PortraitConfig,
    get_cast_entry,
    get_cast_registry,
    list_cast_ids,
)
from .npc_state import (
    NPCCardState,
    NPCScheduleState,
    NPCState,
    NpcAvailability,
    NpcEmotion,
    NpcInteractionMode,
    NpcSoftAlignmentHint,
    NpcStance,
    NpcTrustTrend,
    build_initial_npc_state,
    initialize_mbam_npc_states,
    initialize_mbam_npc_states_from_case_state,
    resolve_world_room_id,
)
from .models import (
    AlibiClaim,
    AlibiMatrix,
    AlibiTruthValue,
    AllyId,
    BenchEvidence,
    BestOutcomeRule,
    CafeEvidence,
    CaseState,
    CastOverlay,
    CharacterOverlay,
    CorridorEvidence,
    CulpritId,
    DifficultyProfile,
    DisplayCaseEvidence,
    DropId,
    DropLocationEvidence,
    EvidencePlacement,
    Helpfulness,
    HiddenCaseSlice,
    MethodId,
    MisdirectorId,
    ResolutionRequirement,
    ResolutionRules,
    RoleAssignment,
    SceneCompletionState,
    SceneGate,
    SceneGates,
    SceneId,
    SoftFailRule,
    TimelineBeat,
    TimelineBeatType,
    TruthEdgeRelation,
    TruthGraph,
    TruthGraphEdge,
    TruthGraphNode,
    TruthNodeType,
    TruthVisibility,
    VisibleCaseSlice,
)
from .generator import (
    DEFAULT_RUNTIME_CLOCK_START,
    MbamSeedFixture,
    SeedInput,
    build_cast_overlay_for_seed,
    build_role_assignment_for_seed,
    generate_case_state,
    generate_case_state_for_seed_id,
    get_seed_fixture,
    resolve_seed_id,
)
from .scaffold import (
    SeedRoleLock,
    ShippedSeed,
    get_seed_role_lock,
    make_default_cast_overlay,
    make_empty_case_state_shell,
    make_roles_assignment_from_seed_lock,
)
from .projection import build_visible_case_projection, build_debug_case_projection

__all__ = [
    "AlibiClaim",
    "AlibiMatrix",
    "AlibiTruthValue",
    "AllyId",
    "BenchEvidence",
    "BestOutcomeRule",
    "CafeEvidence",
    "CaseState",
    "CaseTruthProvider",
    "CastIdentityEntry",
    "FixedCastId",
    "IdentityRole",
    "CastOverlay",
    "CharacterOverlay",
    "CorridorEvidence",
    "CulpritId",
    "DifficultyProfile",
    "DisplayCaseEvidence",
    "DropId",
    "DropLocationEvidence",
    "EvidencePlacement",
    "DEFAULT_RUNTIME_CLOCK_START",
    "Helpfulness",
    "HiddenCaseSlice",
    "MbamSeedFixture",
    "MbamCaseBundle",
    "MethodId",
    "MisdirectorId",
    "ResolutionRequirement",
    "ResolutionRules",
    "RoleAssignment",
    "SceneCompletionState",
    "SceneGate",
    "SceneGates",
    "SceneId",
    "SeedInput",
    "SeedRoleLock",
    "ShippedSeed",
    "SoftFailRule",
    "TimelineBeat",
    "TimelineBeatType",
    "TruthEdgeRelation",
    "TruthGraph",
    "TruthGraphEdge",
    "TruthGraphNode",
    "TruthNodeType",
    "TruthVisibility",
    "VisibleCaseSlice",
    "build_cast_overlay_for_seed",
    "build_role_assignment_for_seed",
    "generate_case_state",
    "generate_case_state_for_seed_id",
    "get_seed_fixture",
    "get_seed_role_lock",
    "make_default_cast_overlay",
    "make_empty_case_state_shell",
    "make_roles_assignment_from_seed_lock",
    "resolve_seed_id",
    "build_visible_case_projection",
    "build_debug_case_projection",
    "PortraitConfig",
    "get_cast_entry",
    "get_cast_registry",
    "list_cast_ids",
    "NpcAvailability",
    "NpcEmotion",
    "NpcInteractionMode",
    "NpcSoftAlignmentHint",
    "NpcStance",
    "NpcTrustTrend",
    "NPCScheduleState",
    "NPCCardState",
    "NPCState",
    "build_initial_npc_state",
    "initialize_mbam_npc_states",
    "initialize_mbam_npc_states_from_case_state",
    "resolve_world_room_id",
]
